In [49]:
import numpy as np
import pandas as pd

In [50]:
a = {'a': 1, 'b': 2}

In [51]:
for i in a:
  print(i)

a
b


In [52]:
#对于for--loop，用两个空格或者三个空格都可以

In [53]:
b = [[1,2,3], [5,6]]

In [54]:
for i in b:
    print(i)

[1, 2, 3]
[5, 6]


In [55]:
for i in b:
    print(i)
    print(len(i))

[1, 2, 3]
3
[5, 6]
2


In [56]:
#the len of results from the for-loop can be more than 1

In [57]:
for i in a:
    print(i)

a
b


In [58]:
#for-loop to dicyionary can be get the index only instead of keys

In [59]:
a = np.array([1,2,3,4])

In [60]:
a = np.array([[1, 2, 3],
             [5, 6, 7]])

In [61]:
a.shape

(2, 3)

In [62]:

b = np.array([[1, 2],
             [3, 4],
             [5, 6],
             [7, 8]])

In [63]:
b.shape

(4, 2)

In [64]:
for i in b:
    print(i)
    print(len(i))

[1 2]
2
[3 4]
2
[5 6]
2
[7 8]
2


In [65]:
nums = [-1, 1, 0, 2]

for num in nums:
    if num % 2:
        print('even number')

even number
even number


In [66]:
total = 0
for i in range(100):
    if total > 10:
        print(total)
        break
    if i % 2 == 0:
        print(i)
        total += 1
        continue

0
2
4
6
8
10
12
14
16
18
20
11


In [67]:
total = 0
for i in range(100):
    if total > 10:
        print(total)
        continue
    if i % 2 == 0:
        print(i)
        total += 1
        break

0


In [68]:
total = 0
for i in range(100):
    if i % 2 == 0:
        print(i)
        total += 1
        continue
    if total > 10:
        print(total)
        break

0
2
4
6
8
10
12
14
16
18
20
11


In [69]:
import numpy as np
a=[1, 2, 3, np.nan]

In [70]:


np.sum(a)

np.float64(nan)

In [71]:
print(np.sum(a))

nan


In [72]:
sum(a)

nan

In [73]:
len(a)

4

In [74]:
np.isnan(a)

array([False, False, False,  True])

In [75]:
b = [ai is np.nan for ai in a]

In [76]:
b

[False, False, False, True]

In [77]:
bool(np.nan)

True

In [78]:
a = [True, False, True, False]
b = [True, True, False, False]

In [79]:
bool(a)

True

In [80]:
bool(b)

True

In [81]:
a = [False, False, False, False]

In [82]:
bool(a)

True

In [83]:
a = [True, False, True, False]
b = [True, True, False, False]

In [84]:
a_np = np.array(a)
b_np = np.array(b)
a_np & b_np # &代表将两个列表进行且运算！

array([ True, False, False, False])

In [85]:
a and b

[True, True, False, False]

In [86]:
a = [True, False, True, False]
b = [True, True, False, False]

In [87]:
a and b

[True, True, False, False]

In [88]:
a or b

[True, False, True, False]

In [89]:
np.logical_not(a)

array([False,  True, False,  True])

np.sum(a)

In [90]:
print(np.sum(a))

2


In [91]:
a = [1, np.nan, '1'] 
b = []
for ai in a:
  try:
      b.append(ai + 2)
  except TypeError as e:
      b.append(ai)
print(b)

[3, nan, '1']


In [92]:
def divide(a, b):
  if b == 0:
    raise ValueError('Cannot divide by 0')
  return int(a / b) 

In [93]:
divide(2, 3)

0

In [94]:
c = divide(1, 0)

ValueError: Cannot divide by 0

In [95]:
divide(b = 1, a = 0)

0

In [96]:
c = divide(b = 1, 0)

SyntaxError: positional argument follows keyword argument (4150597775.py, line 1)

In [97]:
c = {'a': 1, 'b': 2}

In [98]:
divide(**c)

0

In [99]:
c = {'a': 1, 'b': 0}

In [100]:
divide(**c)

ValueError: Cannot divide by 0

In [101]:
divide(1)

TypeError: divide() missing 1 required positional argument: 'b'

In [102]:
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [4, 5, 6, 7]},
                  index=[3, 2, 1, 0])

In [103]:
df

a  b
3  1  4
2  2  5
1  3  6
0  4  7

In [104]:
for i in df.index:
    print(i)

3
2
1
0


In [105]:
for i in range(df.shape[0]):
    print(i)

0
1
2
3


In [106]:
for i in df:
    print(i)

a
b


In [107]:
for i in df.columns:
    print(i)

a
b


In [108]:
df.a.mean()

np.float64(2.5)

In [109]:
df.mean().a

np.float64(2.5)

In [110]:
df['a'].mean()

np.float64(2.5)

In [111]:
df.loc[:, 'a'].mean()

np.float64(2.5)

In [112]:
df.iloc[:, 0].mean()

np.float64(2.5)

In [113]:
df.mean()['a']

np.float64(2.5)

In [114]:
df.mean()[0]

/var/folders/s1/2r578vx153d8cmbdps9ln15m0000gn/T/ipykernel_1404/2861576022.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.mean()[0]


np.float64(2.5)

In [115]:
df.loc[:1, 'b']

3    4
2    5
1    6
Name: b, dtype: int64

In [116]:
df.iloc[:1, 1]

3    4
Name: b, dtype: int64

In [117]:
df['total'] = df.a + df.b

In [118]:
df

a  b  total
3  1  4      5
2  2  5      7
1  3  6      9
0  4  7     11

In [119]:
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [4, 5, 6, 7]},
                  index=[3, 2, 1, 0])

In [120]:
df

a  b
3  1  4
2  2  5
1  3  6
0  4  7

In [121]:
df.loc[:, 'total'] = df.a + df.b

In [122]:
df

a  b  total
3  1  4      5
2  2  5      7
1  3  6      9
0  4  7     11

In [123]:
Z = np.zeros(140)
F = np.full(140, np.nan)

In [124]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [125]:
F

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [126]:
a = np.arange(140)

In [127]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139])

In [128]:
Z3 = np.zeros(140).reshape(10, -1)
for i,j in zip(range(1, 11), range(1, 14)):
    Z3[i-1,j-1] = i+j
print(Z3)

[[ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  8.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 18.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 20.  0.  0.  0.  0.]]


In [129]:
z = np.arange(140).reshape(10, -1)

In [130]:
z

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13],
       [ 14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27],
       [ 28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
         41],
       [ 42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
         55],
       [ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
         69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
         83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
         97],
       [ 98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111],
       [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
        125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139]])

In [131]:
z[1,1]

np.int64(15)

In [132]:
Z3 = np.zeros(140).reshape(10, -1)
for i in range(1, 11):
    for j in range(1, 15):
        Z3[i-1,j-1] = i+j
print(Z3)

[[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.]]


In [133]:
F3 = np.zeros(140).reshape(10, -1)
for i in range(1, 11):
    for j in range(1, 15):
        F3[i-1,j-1] = i - j
print(F3)

[[  0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10. -11. -12. -13.]
 [  1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10. -11. -12.]
 [  2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10. -11.]
 [  3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]
 [  4.   3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9.]
 [  5.   4.   3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.]
 [  6.   5.   4.   3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.]
 [  7.   6.   5.   4.   3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.]
 [  8.   7.   6.   5.   4.   3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.]
 [  9.   8.   7.   6.   5.   4.   3.   2.   1.   0.  -1.  -2.  -3.  -4.]]


In [134]:
sum = 0
for i in range(10):
    for j in range(14):
        mid = (Z3[i,j] - F3[i,j])**2
        sum = sum + mid
print(sum)


40600.0


In [139]:
A = np.arange(1, 11).reshape(10, 1)
B = np.arange(1, 15).reshape(1, 14)

In [142]:
Z4 = np.zeros(140).reshape(10, 14) + A + B

In [143]:
Z4

array([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,
        16.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
        17.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
        19.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,
        20.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.,
        21.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.,
        22.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
        23.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
        24.]])

In [144]:
F4 = np.zeros(140).reshape(10, 14) + A - B

In [145]:
F4

array([[  0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.,
        -11., -12., -13.],
       [  1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9.,
        -10., -11., -12.],
       [  2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,
         -9., -10., -11.],
       [  3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,
         -8.,  -9., -10.],
       [  4.,   3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,
         -7.,  -8.,  -9.],
       [  5.,   4.,   3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,
         -6.,  -7.,  -8.],
       [  6.,   5.,   4.,   3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,
         -5.,  -6.,  -7.],
       [  7.,   6.,   5.,   4.,   3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,
         -4.,  -5.,  -6.],
       [  8.,   7.,   6.,   5.,   4.,   3.,   2.,   1.,   0.,  -1.,  -2.,
         -3.,  -4.,  -5.],
       [  9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,   1.,   0.,  -1.,
         -2.,  -3

In [146]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [147]:
a[2] = a[1]

In [148]:
a

[1, 2, 2, 4, 5, 6, 7, 8, 9]

In [155]:
def swap(x):
    for i in range(int(len(x) / 2)):
        a = x[i*2 + 1]
        x[i*2 + 1] = x[i*2]
        x[i*2] = a
    return x

In [156]:
x = [1, 2, 3, 4]

In [157]:
swap(x)

[2, 1, 4, 3]

In [162]:
list = [2]
for i in range(3, 101, 2):
    for j in range(2, i):
        if i % j == 0:
            break
    else:
        list.append(i)

In [163]:
list

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [173]:
def is_palindrome(s):
    if len(s) % 2 == 0:
        for i in range(int(len(s)/2)):
            if s[i] == s[len(s) - i - 1]:
                continue
            else:
                print('Flase')
        print('True')
    else:
        for j in range(int((len(s)-1)/2)):
            if s[j] == s[len(s) - j -1]:
                continue
            else:
                print('False')

In [174]:
is_palindrome('helleh')

True


In [175]:
s = 'helleh'
for i in range(int(len(s)/2)):
    print(i)

0
1
2


In [176]:
len(s)

6

In [177]:
is_palindrome('abc')

False


In [178]:
is_palindrome('abba')

True


In [179]:
 is_palindrome("abba") 

True


In [180]:
def is_palindrome(s):
    if len(s) % 2 == 0:
        for i in range(int(len(s)/2)):
            if s[i] == s[len(s) - i - 1]:
                continue
            else:
                print('Flase')
        print('True')
    else:
        for j in range(int((len(s)-1)/2)):
            if s[j] == s[len(s) - j -1]:
                continue
            else:
                print('False')
        print('True')

In [181]:
is_palindrome('abba')

True


In [182]:
with open('wordlist.txt', 'r') as file:
    word_list = file.readlines() 
word_list = [word.strip() for word in word_list]


FileNotFoundError: [Errno 2] No such file or directory: 'wordlist.txt'

In [183]:
s = 'hello'

In [184]:
s[1] + s[2]

'el'

In [185]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [186]:
a = {}

In [188]:
a = {'a': 3, 'b': 7, 'g': 18}

In [191]:
max(a.key())

AttributeError: 'dict' object has no attribute 'key'

In [192]:
for i in a:
    print(i)

a
b
g


In [193]:
my_dict = {'a': 10, 'b': 20, 'c': 15, 'd': 25}
 
# 使用max函数找到值最大的键值对
max_item = max(my_dict.items(), key=lambda item: item[1])

In [194]:
max_item

('d', 25)

In [195]:
my_dict = {'a': 10, 'b': 20, 'c': 15, 'd': 25}

In [201]:
my_dict['a']

10

In [212]:
df = pd.DataFrame({'班级': ['A', 'B', 'A', 'B'],
                   '姓名': ['赵云', '张飞', '刘备', '诸葛亮'],
                   '语文': np.random.rand(4) * 100,
                   '数学': np.random.rand(4) * 100}).round()

In [213]:
df

班级   姓名    语文    数学
0  A   赵云  53.0  74.0
1  B   张飞  89.0  78.0
2  A   刘备  48.0  38.0
3  B  诸葛亮  37.0  37.0

In [214]:
df.round()
#round()函数的功能室将dataframe中的数据化为一位小数

班级   姓名    语文    数学
0  A   赵云  53.0  74.0
1  B   张飞  89.0  78.0
2  A   刘备  48.0  38.0
3  B  诸葛亮  37.0  37.0

In [215]:
df = df.round()

In [216]:
df

班级   姓名    语文    数学
0  A   赵云  53.0  74.0
1  B   张飞  89.0  78.0
2  A   刘备  48.0  38.0
3  B  诸葛亮  37.0  37.0

In [219]:
df.groupby('班级')

In [220]:
print(df.groupby('班级'))

In [227]:
df.groupby('班级', as_index = False)['语文']['数学'].mean()

IndexError: Column(s) 语文 already selected

In [228]:
df.groupby('班级', as_index = False)['语文']['数学'].mean()

IndexError: Column(s) 语文 already selected

In [229]:
df = pd.DataFrame({'班级': ['A', 'B', 'A', 'B'],
                   '姓名': ['赵云', '张飞', '刘备', '诸葛亮'],
                   '语文': np.random.rand(4) * 100,
                   '数学': np.random.rand(4) * 100}).round()

In [231]:
df.groupby('班级', as_index = False)['数学'].mean()

班级    数学
0  A  13.0
1  B  68.5

In [232]:
df.groupby('班级')['数学'].mean()

班级
A    13.0
B    68.5
Name: 数学, dtype: float64

In [233]:
df.groupby('班级').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [1]:
a = {'a' : 1, 'b' : 2}

In [2]:
for i in a:
    print(i)

a
b


In [7]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [8]:
a.shape

(2, 4)

In [11]:
b = a.reshape(4, 2)

In [10]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
b.shape

(4, 2)

In [14]:
for i in b:
    print(i)

[1 2]
[3 4]
[5 6]
[7 8]


In [16]:
nums = [-1, 1, 0, 2]

for num in nums:
    if num % 2:
        print(num)
        print('even number')

-1
even number
1
even number


In [19]:
total = 0
for i in range(100):
    print(i)
    if total > 10:
        break
    if i % 2 == 0:
        continue
    total = total + 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [18]:
print(total)

11


In [20]:
total = 0
for i in range(100):
    if total > 10:
        continue
    if i % 2 == 0:
        break
    total = total + 1

In [21]:
print(total)

0


In [22]:
import numpy as np
a=[1, 2, 3, np.nan]

In [23]:
np.sum(a)

np.float64(nan)

In [24]:
sum(a)

nan

In [25]:
b = np.sum(a)

In [26]:
b

np.float64(nan)

In [27]:
a = [True, False, True, False]
b = [True, True, False, False]

In [28]:
bool(a)

True

In [29]:
a and b

[True, True, False, False]

In [30]:
a or b

[True, False, True, False]

In [31]:
np.sum(a)

np.int64(2)

In [33]:
np.logical_not(a)

array([False,  True, False,  True])

In [35]:
a_np = np.array(a)
b_np = np.array(b)
a_np & b_np

array([ True, False, False, False])

In [36]:
a_np

array([ True, False,  True, False])

In [37]:
b_np

array([ True,  True, False, False])

In [38]:
a = [1, np.nan, '1'] 
b = []
for ai in a:
  try:
      b.append(ai + 2)
  except TypeError as e:
      b.append(ai)

In [39]:
a

[1, nan, '1']

In [40]:
b

[3, nan, '1']

In [48]:
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [4, 5, 6, 7]},
                  index=[3, 2, 1, 0])

In [42]:
for i in df.index:
    print(i)

3
2
1
0


In [44]:
for i in range(df.shape[0]):
    print(i)
# index 和 shape[0] 的区别！

0
1
2
3


In [45]:
for i in df.columns:
    print(i)

a
b


In [46]:
for i in df:
    print(i)

a
b


In [49]:
df.loc[:1, 'b']

3    4
2    5
1    6
Name: b, dtype: int64

In [51]:
df.iloc[:1, 1]

3    4
Name: b, dtype: int64

In [52]:
df

a  b
3  1  4
2  2  5
1  3  6
0  4  7

In [53]:
df['total'] = df.a + df.b

In [54]:
df

a  b  total
3  1  4      5
2  2  5      7
1  3  6      9
0  4  7     11

In [55]:
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [4, 5, 6, 7]},
                  index=[3, 2, 1, 0])

In [56]:
df

a  b
3  1  4
2  2  5
1  3  6
0  4  7

In [57]:
df.loc[:, 'total'] = df.a + df.b

In [58]:
df

a  b  total
3  1  4      5
2  2  5      7
1  3  6      9
0  4  7     11

In [59]:
def divide(a, b):
  if b == 0:
    raise ValueError('Cannot divide by 0')
  return int(a / b) 

In [60]:
divide(1)

TypeError: divide() missing 1 required positional argument: 'b'

In [61]:
c = {'b' : 1, 'a' : 0}

In [62]:
divide(**c)

0

In [63]:
c = {'a' : 1, 'b' : 2}

In [64]:
divide(**c)

0

In [65]:
c

{'a': 1, 'b': 2}

In [66]:
divide(**c)

0

In [67]:
c = divide(b = 1, 0)

SyntaxError: positional argument follows keyword argument (4150597775.py, line 1)

In [68]:
divide(b = 1, a = 0)

0

In [69]:
c = divide(1, 0)

ValueError: Cannot divide by 0

In [70]:
divide(2, 3)

0