In [1]:

# Always explore your data
# We have 3 files that simulated a potential AB test that is measuring clicks and views.

# sim_ab_test_assignment.csv
# sim_ab_test_clicks.csv
# sim_ab_test_views.csv

In [2]:
# Task 1
# Load the files into sensible variable names using numpy. Hint: loading strings vs numbers may be different!

In [119]:
import numpy as np
assign = np.loadtxt('sim_ab_test_assignment.csv', dtype = str, delimiter = ',')

In [9]:
clicks = np.loadtxt('sim_ab_test_clicks.csv', delimiter = ',')

In [10]:
views = np.loadtxt('sim_ab_test_views.csv', delimiter = ',')

In [11]:
# Task 2
# Examine the data a bit

# What are the dimensions for each of the CSVs?
# This should bring up some questions, what are our guesses?
# Can we look at some sample values in the data?
# Try looking at the first few rows and columns
# Try looking at the last few rows and columns

In [12]:
assign.shape

(1000,)

In [13]:
clicks.shape

(1000, 14)

In [14]:
views.shape

(1000, 14)

In [19]:
assign[: 5]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U5')

In [20]:
clicks[:3, :]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 3., 0., 0., 0., 0.]])

In [21]:
views[:3, :]

array([[ 0.,  6.,  0.,  0.,  0.,  0.,  0.,  3.,  8.,  3.,  0.,  0.,  0.,
         0.],
       [ 7., 37.,  0.,  0., 13., 12., 26.,  0., 16.,  1.,  0., 25.,  4.,
         0.],
       [ 5.,  0.,  9.,  0.,  7.,  0.,  0.,  0.,  8., 17.,  5.,  6.,  3.,
         0.]])

In [22]:
# Task 3
# It's important to track a few summary statistics about data, statistics that will let us know if the data is bad.

# Calculate some of these statistics
# Use print() to print out a human readable message that includes these statistics.

In [23]:
# find nan

In [25]:
np.isnan(clicks)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [26]:
np.isnan(clicks).any()

np.False_

In [27]:
any_negs = np.min(clicks) < 0

In [28]:
any_negs

np.False_

In [30]:
(clicks <= views).all()

np.True_

In [31]:
zero_frequency = (clicks == 0).mean()

In [32]:
zero_frequency

np.float64(0.8257142857142857)

In [33]:
# Task 4
# What kind of mathematical notation would you use to describe our data? Now use that notation to express (no code)

# total clicks over all users / total views over all users
# Average click through rate
# Now write the code to do these calculations

In [34]:
total_clicks = clicks.sum()

In [35]:
total_clicks

np.float64(3727.0)

In [37]:
total_views = views.sum()

In [38]:
total_views

np.float64(70428.0)

In [93]:
ctr_1 = total_clicks / total_views

In [94]:
tot_clicks_user = np.apply_along_axis(np.sum, 1, clicks)

In [95]:
tot_views_user = np.apply_along_axis(np.sum, 1, views)

In [96]:
ctr_2 = (tot_clicks_user / tot_views_user).mean()

In [97]:
ctr_2

np.float64(0.053078945894088896)

In [98]:
ctr_1

np.float64(0.05291929346282728)

In [99]:
# Task 5
# Let's compare the 2 metrics:

# Remove one of the most active members from the data and re-calculate both metrics.
# How would you compare the metric before/after the removal? Calculate something and print() it out.
# Which metric would you recommend?

In [100]:
tot_clicks_user.argmax()

np.int64(733)

In [101]:
tot_views_user.argmax()

np.int64(149)

In [102]:
tot_clicks_user2 = tot_clicks_user.copy()

In [103]:
tot_clicks_user2 = np.delete(tot_clicks_user2, tot_views_user.argmax())

In [104]:
tot_views_user2 = tot_views_user.copy()

In [105]:
tot_views_user2 = np.delete(tot_views_user2, tot_views_user.argmax())

In [106]:
len(tot_clicks_user2)

999

In [107]:
len(tot_views_user2)

999

In [108]:
ctr_m1 = np.sum(tot_clicks_user2) / np.sum(tot_views_user2)

In [109]:
ctr_m1

np.float64(0.05291698097095117)

In [110]:
ctr_m2 = (tot_clicks_user2 / tot_views_user2).mean()

In [111]:
ctr_m2

np.float64(0.053078131810330366)

In [112]:
# Task 6
# Calculate the recommended metric for each of the treatment groups.

In [122]:
is_treat = assign == 'True'

In [124]:
is_control = ~is_treat

In [125]:
np.sum(tot_clicks_user[is_treat])

np.float64(380.0)

In [127]:
np.sum(tot_clicks_user[is_treat]) / np.sum(tot_views_user[is_treat])

np.float64(0.10317675807765408)

In [129]:
(tot_clicks_user[is_treat] / tot_views_user[is_treat]).mean()

np.float64(0.10428005022713495)

In [130]:
np.sum(tot_clicks_user[is_control]) / np.sum(tot_views_user[is_control])

np.float64(0.05014607835792943)